device:
  layer: rpi5
  hostname: opencal
  user1: opencal
  user1passhash: '$6$1uzTVCykHwpOKc8.$y7u5R4Xi81M5SRL9BjtSWLIQElmYdKFmFrXeeGA8o5Rkz5DQk6FG749Deg6NlMuhBL2XgzWxakWrPiBIUGfUx/'
  user1groups: i2c,spi
  ssh: y

ssh:
  pubkey_only: n

image:
  layer: image-rpios
  name: opencal-v0.1
  boot_part_size: 512M
  root_part_size: 4G
  compression: zstd

sys:
  mirrors: >-
    deb http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
    deb http://deb.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
    deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
    deb http://archive.raspberrypi.com/debian/ bookworm main

layer:
  base: bookworm-minbase

