device:
  layer: rpi5
  hostname: opencal
  user1: opencal
  user1pass: OpenCAL1!
  user1sudo: nopasswd

image:
  layer: image-rpios
  name: opencal
  boot_part_size: 512M
  root_part_size: 4G
  compression: zstd

layer:
  base: bookworm-minbase
  app: opencal
